---
apiVersion: "apps/v1beta2"
kind: Deployment
metadata:
  name: "httptogrpc-v0-1-0-snapshot"
  labels:
    appName: httptogrpc
    appNameVersion: "httptogrpc-v0-1-0-snapshot"
spec:
  replicas: 1
  selector:
    matchLabels:
      appNameVersion: "httptogrpc-v0-1-0-snapshot"
  template:
    metadata:
      labels:
        appName: httptogrpc
        appNameVersion: "httptogrpc-v0-1-0-snapshot"
    spec:
      restartPolicy: Always
      containers:
        - name: httptogrpc
          image: "httptogrpc:0.1.0-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          env:
            - name: "RP_APP_NAME"
              value: httpToGrpc
            - name: "RP_APP_TYPE"
              value: basic
            - name: "RP_APP_VERSION"
              value: "0.1.0-SNAPSHOT"
            - name: "RP_ENDPOINTS"
              value: HTTP
            - name: "RP_ENDPOINTS_COUNT"
              value: "1"
            - name: "RP_ENDPOINT_0_BIND_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_ENDPOINT_0_BIND_PORT"
              value: "8080"
            - name: "RP_ENDPOINT_0_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_ENDPOINT_0_PORT"
              value: "8080"
            - name: "RP_ENDPOINT_HTTP_BIND_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_ENDPOINT_HTTP_BIND_PORT"
              value: "8080"
            - name: "RP_ENDPOINT_HTTP_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_ENDPOINT_HTTP_PORT"
              value: "8080"
            - name: "RP_JAVA_OPTS"
              value: "-Dconfig.resource=rp-application.conf"
            - name: "RP_KUBERNETES_POD_IP"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_KUBERNETES_POD_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.name"
            - name: "RP_MODULES"
              value: common
            - name: "RP_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: "RP_PLATFORM"
              value: kubernetes
          ports:
            - containerPort: 8080
              name: http
          volumeMounts: []
          command:
            - "/rp-start"
          args:
            - "bin/httptogrpc"
      volumes: []
---
apiVersion: v1
kind: Service
metadata:
  labels:
    appName: httptogrpc
  name: httptogrpc
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    appName: httptogrpc
---
apiVersion: "extensions/v1beta1"
kind: Ingress
metadata:
  name: httptogrpc
spec:
  rules:
    - host: "superservice.com"
      http:
        paths:
          - backend:
              serviceName: httptogrpc
              servicePort: 8080
